apps/cart/urls.py
from django.conf.urls import url

from apps.cart import views
urlpatterns = [

    url(r'^cart$', views.CartinfoView.as_view(), name='cartinfo'),

    url(r'^add$', views.CartAddView.as_view(), name='cartadd'),

    url(r'^listadd$', views.CartListAddView.as_view(), name='listadd'),

    url(r'^update$', views.CartUpdateView.as_view(), name='update'),

    url(r'^delete', views.CartDeleteView.as_view(), name='delete'),

]

apps/goods/urls.py
from django.conf.urls import url

from apps.goods import views

urlpatterns = [
    #进入首页
    url(r'^index$', views.IndexView.as_view(), name='index'),

    #商品详情页面
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    #商品列表详情
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$',views.ListView.as_view(), name='list'),

    # url(r'^car_add/(?P<goods_id>\d+)/(?P<number>\d+)$',views.CarAddView.as_view(), name='car_add'),


]

apps/orders/urls.py
from django.conf.urls import url

from apps.orders import views

urlpatterns = [

    url(r'^place$', views.PlaceOrderView.as_view(), name='place'),

]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.users import views

urlpatterns = [

    # 视图函数
    # url(r'^register$', views.register, name='register'),
    # url(r'^do_register$', views.do_register, name='do_register'),


    # 类函数 (注意: as_view需要添加括号)
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^active/(?P<token>.+)$', views.ActiveView.as_view(), name='active'),

    url(r'^order$', views.UserOrderView.as_view(), name='order'),           # /users/order
    url(r'^address$', views.UserAddressView.as_view(), name='address'),     # /users/address
    url(r'^$', views.UserInfoView.as_view(), name='info'),                  # /users




    # View -> LoginRequiredView(重写as_view) -> UserAddressView
    # TemplateView -> LoginRequiredView2(重写as_view) -> UserAddressView

    # url(r'^address$', login_required(views.UserAddressView.as_view()), name='address'),     # /users/address
    # url(r'^address$', login_required(views.address), name='address'),     # /users/address

]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # # 包含tinymce urls配置文件
    # url(r'^tinymce/', include('tinymce.urls')),


    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('apps.goods.urls', namespace='goods')),

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import View
from django_redis import get_redis_connection
from redis import StrictRedis

from apps.goods.models import GoodsSKU
from apps.my_apps.aps import extension
from utils.common import LoginRequiredMixin
from apps.my_apps.aps import extension


#购物车页面
class CartinfoView(LoginRequiredMixin,View):

    def get(self, request):

        # 判断用户是否登陆
        # is_authenticated是Django内置的user的方法：用来判断用户是否登陆
        if request.user.is_authenticated():
            pass
            # 接收数据：user_id，sku_id，count

        # strict_redis对象 = get_redis_connection("default")：用于链接redis数据的得到可以获取数据的对象
        strict_redis = get_redis_connection("default")
        # strict_redis = StrictRedis()

        # 获取用户id
        user_id = request.user.id

        # 如果redis中不存在，会返回None
        # 取得hash类型的所有数据（类似多个字典）
        cart_dict = strict_redis.hgetall("cart_%s" % user_id)

        goods_dict = {}

        for i in cart_dict:

            cartgoods = GoodsSKU.objects.get(id=int(i))

            #商品对象添加新属性 =  商品对象取得.商品单价 × 商品数量（通过商品id.key值取得value）
            cartgoods.amunt = "%.2f"%(float(cartgoods.price) * int(cart_dict[i]))

            goods_dict[cartgoods] = int(cart_dict[i])


        goods_total = extension.car_info(request)


        data = {
            'cart_dict':cart_dict,
            'goods_dict':goods_dict,
            'goods_total':goods_total,

        }

        return render(request, 'cart.html', data)


#商品详情页：商品添加到购物车
class CartAddView(LoginRequiredMixin,View):

    def post(self,request):


        # 判断用户是否有登录
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登录'})

        # 获取用户提交的参数
        user_id = request.user.id
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # todo: 判断参数合法性
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '请求参数不能为空'})
        # 检验购买数量的合法性
        try:
            count = int(count)
        except:
            return JsonResponse({'code': 3, 'errmsg': '购买数量格式不正确'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 4, 'errmsg': '商品不存在'})
        # todo: 业务处理: 添加商品到Redis数据库中
        # 尝试获取redis中商品的购买数量
        # cart_1: {'1':'2', '2':'2'}
        strict_redis = get_redis_connection()
        key = 'cart_%s' % user_id
        # 获取不到会返回None
        val = strict_redis.hget(key, sku_id)
        if val:
            count += int(val)

        # 校验库存是否充足
        if count > sku.stock:
            return JsonResponse({'code': 5, 'errmsg': '库存不足'})

        # 更新商品数量
        strict_redis.hset(key, sku_id, count)

        # todo: 计算购物车中商品的总数量
        #调用子封装包my_apps.返回当前登陆用户购物车商品数量
        cart_count = extension.car_info(request)

        # 响应json数据
        return JsonResponse({'code': 0, 'message': '添加到购物车成功',
                             'cart_count': cart_count})

#ajax 修改购物车商品数量
class CartUpdateView(View):

    def post(self,request):

        #判断用户是否登陆
        if not request.user.is_authenticated():

            return JsonResponse({"code":1,"errmsg":"请先登陆"})

        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        #判断参数是否完整
        if not all([sku_id,count]):
            return JsonResponse({"code":2,"errmsg":"参数不能为空"})

        #获取商品，从而判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except:
            return JsonResponse({"code":3,"errmsg":"商品不存在"})

        #转为整数
        try:
            count = int(count)
        except:
            return JsonResponse({"code":4,"errmsg":"购买数量需为整"})

        #判断库存
        if count > sku.stock:
            return JsonResponse({"code":5,"errmsg":"库存不足"})

        strict_redis = get_redis_connection()

        key = "cart_%s"%request.user.id

        #todo           用户id；商品id；商品数量;
        strict_redis.hset(key,sku_id,count)

        return JsonResponse({"code":0,"errmsg":"商品数量变动"})

#ajax 删除购物车商品
class CartDeleteView(View):

    def post(self,request):

        if not request.user.is_authenticated:

            return JsonResponse({"code":1,"errmsg":"请先登陆"})

        sku_id = request.POST.get("sku_id")

        key = "cart_%s"%request.user.id

        strict_redis = get_redis_connection()

        strict_redis.hdel(key,sku_id)

        # return redirect(reverse('cart:cartinfo'))
        # return redirect("/cart/cart")
        return JsonResponse({"code": 0, "errmsg": "已删除"})

#ajax 商品列表添加商品到购物车
class CartListAddView(View):

    def post(self,request):



        if not request.user.is_authenticated:

            return JsonResponse({"code":1,"errmsg":"请先登陆"})



        sku_id = request.POST.get("sku_id")

        if sku_id=='':

            cart_count = extension.car_info(request)
            return JsonResponse({"cart_count":cart_count})

        strict_redis = get_redis_connection()
        user_id = "cart_%s" % request.user.id
        sku_dict = strict_redis.hgetall(user_id)


        try:
            count = sku_dict.get(sku_id.encode())
        except Exception as e:
            print(e)


        amount = 0

        if not count == None:
            goods = sku_dict[sku_id.encode()]
            print("......",goods)
            amount = int(goods.decode()) + 1

        else:
            amount+=1


        strict_redis.hset(user_id,sku_id,amount)

        cart_count = extension.car_info(request)

        return JsonResponse({"code":0,"errmsg":"添加成功","cart_count":cart_count})

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles%}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}天天生鲜-首页{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {#  顶部js导入 #}
    {% block top_js %}
    {% endblock %}

</head>
<body>

    {# 界面顶部的信息栏 #}
    {% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">

                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                    <a href="{% url 'users:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'users:register' %}">注册</a>
                </div>
                {% endif %}


                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'users:info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cartinfo' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'users:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {# 搜索栏 #}
    {% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">

            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>

        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:cartinfo' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
    {% endblock %}


    {# 主体内容 #}
    {% block body %}
    {% endblock %}

    {# 版权信息 #}
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888    京ICP备*******8号</p>
    </div>

    {# 界面底部js #}
    {% block bottom_js %}
    {% endblock %}

</body>
</html>

templates/base_user_center.html
{# 用户中心父模板: 用户中心的3个子界面 #}
{% extends 'base_no_cart.html' %}

{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block page_title %}
用户中心
{% endblock %}

{% block body %}
<div class="main_con clearfix">
    {# 左侧部分内容 #}
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'users:info' %}"
                   {% if which_page == 0 %}class="active"{% endif %}
            >· 个人信息</a></li>

            <li><a href="{% url 'users:order' %}"
                    {% if which_page == 1 %}class="active"{% endif %}
            >· 全部订单</a></li>
            <li><a href="{% url 'users:address' %}"
                    {% if which_page == 2 %}class="active"{% endif %}
            >· 收货地址</a></li>
        </ul>
    </div>

    {# 右侧部分内容 #}
    {% block right_body %}
    {% endblock %}

</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品详情</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>



{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>

				<ul class="subnav">
					 {# 显示所有类别 #}
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' forloop.counter 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

				</ul>

			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>


    {% csrf_token %}

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.title }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">

				<a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>

			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus  %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
					{% endfor %}


				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.spu.desc|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
    <div class="popup_con">
		<div class="popup">
			<p>商品添加成功！</p>
		</div>
{% endblock %}

{% block bottom_js %}
    {% load staticfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

    update_goods_amount();

    //todo // 更新购物商品的总价
    function update_goods_amount() {

        // 获取商品的单价和购买数量
        //单价
        var price = $('.show_pirze').children('em').text();
        //数量
        var count = $('.num_show').val();
        // 更新数量和总价，规整类型
        price = parseFloat(price);
        count = parseInt(count);

        var tatal_amount = price * count;

        $('.total').children('em').html(tatal_amount.toFixed(2)+'元');
    }
   //todo 新增商品购买数量
    $('.add').click(function () {

        var count = $('.num_show').val();
        count = parseInt(count);
        count += 1 ;
        $('.num_show').val(count);
        update_goods_amount();

    })
    //todo 减少商品购买数量
    $('.minus').click(function () {

        var count = $('.num_show').val();
        if(count>1){
            count = parseInt(count);
            count -= 1 ;
        }

        $('.num_show').val(count);
        update_goods_amount();

    })
    // 手动输入商品购买数量

    //todo 手动输入商品购买数量
    $('.num_show').blur(function () {
        // 获取用户输入的商品数量
        var count = $(this).val();
        // 判断输入参数的合法性
        // if (不是数字 || 空字符串  || 数值小于1)  都为不合法
        if (isNaN(count) || count.trim().length < 1 || parseInt(count) < 1) {
            // 输入数量的不合法
            count = 1;
        }
        // 重新设置商品的数量
        $(this).val(parseInt(count));
        update_goods_amount();
    });


         // todo: 点击添加到购物车时, 通过ajax发起post请求,添加商品到购物车
         $('#add_cart').click(function() {

             // 获取商品id和购买数量
             var sku_id = $(this).attr('sku_id');
             var count = $('.num_show').val();
             var token = $('input[name="csrfmiddlewaretoken"]').val();
              /*
              alert(token);
              alert(sku_id);
              alert(count);
              */
             // Post请求参数
             var params = {
                 'sku_id': sku_id,
                 'count': count,
                 'csrfmiddlewaretoken': token
             };



             $.post('/cart/add', params, function (result) {
                 // result: 服务器返回的数据:
                 // {'code': 4, 'errmsg': '库存不足'}
                 // {'code': 0, 'message': '添加到购物车成功', 'cart_count': cart_count}
                 if (result.code == 0) {
                     // 添加商品到购物车成功
                     $('#show_count').html(result.cart_count);
                      $('.popup_con').fadeIn('fast', function() {

                            setTimeout(function(){
                                $('.popup_con').fadeOut('fast',function(){

                                });
                            },200)

                        });
                 } else {
                     // 提示出错信息
                     alert(result.errmsg);
                 }
             })
         });





		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		});

	</script>
{% endblock %}
	
</body>
</html>

templates/list.html
{% extends 'base.html' %}

{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品列表</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>

{% block body %}
    {% csrf_token %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                      {# 显示所有的类别 #}
                    {% for category in categories %}
                        {# 默认跳转到某个分类商品列表的第一页 #}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="#">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">

				    {# 显示排序条件: 并设置当前选中的是哪一项 #}
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot"
                   {% if sort == 'hot' %}class="active"{% endif %}>人气</a>


			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in page %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="detail.html">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车" sku_id ="{{ sku.id }}"></a>
                        </div>
                    </li>
				{% endfor %}


			</ul>

			<div class="pagenation">

				 {# 显示分页信息 #}
                {% if page.has_previous %}

                    <a href="{% url 'goods:list' category.id page.previous_page_number %}?sort={{ sort }}"
                    >上一页</a>

                {% endif %}

                {% for index in page_list %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if index == page.number %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}

                {% if page.has_next %}
                    <a href="{% url 'goods:list' category.id page.next_page_number %}?sort={{ sort }}"
                    >下一页</a>
                {% endif %}

			</div>
		</div>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>商品添加成功！</p>
		</div>
{% endblock %}
{% block bottom_js %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">

     var token  = $('input[name= "csrfmiddlewaretoken"]').val();

    $('.add_goods').click(function () {

        var sku_id = $(this).attr('sku_id');

        var count = 1;

        var params = {
                 'sku_id': sku_id,
                 'count': count,
                 'csrfmiddlewaretoken': token
             };

         $.post('/cart/add', params, function (result) {
             // result: 服务器返回的数据:
             // {'code': 4, 'errmsg': '库存不足'}
             // {'code': 0, 'message': '添加到购物车成功', 'cart_count': cart_count}
             if (result.code == 0) {
                 // 添加商品到购物车成功
                 $('#show_count').html(result.cart_count);
                  $('.popup_con').fadeIn('fast', function() {

                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){

                            });
                        },200)

                    });
             } else {
                 // 提示出错信息
                 alert(result.errmsg);
             }
         })

    });




    </script>

{% endblock %}

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="login_top clearfix">
    <a href="{% url 'goods:index' %}" class="login_logo">
        <img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'users:register' %}">立即注册</a>
            </div>
            <div class="form_input">


                <form method="post">

                    {% csrf_token %}

                    <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" name="password" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">

                        {# 显示登录出错信息 #}
                        <div style="color: red">{{ errmsg }}</div>

                        <input type="checkbox" name="remember">
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <input type="submit" name="" value="登录" class="input_submit">
                </form>


            </div>
        </div>
    </div>
</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>